services:
  - type: web
    name: res-app
    env: node
    region: oregon
    buildCommand: npm install && npm run build --prefix client
    startCommand: node server/index.js
    envVars:
      MONGODB_URI: your_mongodb_uri